include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - '**/build/**'
    - '**/.dart_tool/**'
    - '**/macos/Flutter/ephemeral/**'
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
