name: flutter_foundation_workspace
publish_to: none

environment:
  sdk: ^3.13.1

workspace:
  - packages/birb_design_system
  - packages/birb_appearance
  - packages/ag_ui_view_state
  - packages/ag_ui_widgets
  - examples/catalog
  - examples/generic_ag_ui

dev_dependencies:
  crypto: ^3.0.7
  flutter_lints: ^6.0.0
